### ISSUE TITLE
Downloading of backup file fails authentication

### ISSUE THREAD

**Issue by dnolan** [ghuntley/atlassian-cloud-backup#4]
The backup process triggers everything correctly, however after the download completes, the downloaded file is only 1kb, even though the one on the server is over 200mb.

I got the same issue when attempting to write a powershell downloader, so I'm wondering if a) its a configuration issue our end, or b) atlassian no longer support the same method for triggering downloads/backups? If you can confirm it works your end then i'll raise it with atlassian.

Opening the zip in a text editor I get the following:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache Server at *****.atlassian.net Port 80</address>
</body></html>
```

**Comment by ghuntley** [comment]
Raise it with Atlassian and come back to me with what they say.

**Comment by dnolan** [comment]
Looks like my fault, didn't realise i needed to be in the administrators group! I can now access the location, although I have noted the filenames are different to the one being searched for and include the timestamp too now eg `Jira_backup_Full_201604011642.zip` and attachments are in a separate zip.
