### ISSUE TITLE
Atlassian are changing the way that they do Cloud backups.

### ISSUE THREAD

**Issue by abrookewood** [ghuntley/atlassian-cloud-backup#5]
This has just started being rolled out and they don't really have much documentation on it. What is clear at the moment is that the WebDav approach is being retired. You can read a bit about it here:
https://jira.atlassian.com/browse/CONF-45003

**Comment by ghuntley** [comment]
Thanks for the heads up @abrookewood

**Comment by pavlovps** [comment]
I suspect this one goes with the previous one: now backup request always fails with 401 response. Cookies seem to be correct, same as after authorization step.

**Comment by abrookewood** [comment]
I've been speaking to them and they don't have a time frame for when this will be rolled out every where. In my case, the new method is in place for Confluence, but the old method is still in place for Jira. They also said that they will implement the following:
1.  Proper documentation on this change 
2.  Timestamp on the backup file name 
3.  Instance URL on the backup file name

**Comment by abrookewood** [comment]
Hi,

There is a work around posted here: https://jira.atlassian.com/browse/CONF-45015

darren.bowen@thirdkindgames.com added a comment:
I also used the bit bucket example for my script.
https://bitbucket.org/atlassianlabs/automatic-cloud-backup/src/174a81f82577397b85b61de564b789466095fb1d/backup.sh?at=master&fileviewer=file-view-default

However, I've since found a way to do this with the new system, in the wait for backup loop rather than attempting to download the file you can instead query its status to see if its complete.
Fetch the following URL in the script
https://$account.atlassian.net/wiki/rest/obm/1.0/getprogress

This returns a json string with details of the backup. If the backup has completed it will have a fileName property which you can use to download the backup as follows:
{"fileName":"temp/filestore/a79ecb00-0e3d-4817-acd6-a52ae3b5e596","size":0,"currentStatus":"Zipping export files.","alternativePercentage":"Estimated progress: 100 %","concurrentBackupInProgress":false}

If it's still creating then the fileName property won't be there so you can continue to wait, e.g:
{"size":0,"currentStatus":"Zipping export files.","alternativePercentage":"Estimated progress: 89 %","concurrentBackupInProgress":false}

Avoid some of the other properties like size (which is always zero) and currentStatus (which says 'Zipping export files' even though the backup is complete.)

**Comment by abrookewood** [comment]
I've incorporated Darren's suggestion and it works. The script below will backup Cloud Confluence on the _new_ backup mechanism. To backup Jira instead, you need to remove the references to 'wiki' in the URLs on lines 24, 29, 36 and 37.

```
<# 
DESCRIPTION: This script backs up Confluence from Atlassian Cloud.
AUTHOR:      Antony Brooke-Wood
SOURCE:      https://bitbucket.org/atlassianlabs/automatic-cloud-backup
             https://github.com/ghuntley/atlassian-cloud-backup/blob/master/src/AtlassianCloudBackupClient/BackupClient.cs
#>

$account     = 'account'
$username    = 'username'
$password    = 'password'
$destination = 'C:\destination'
$attachments = $false
$cronitor    = 'cronitor'

$today       = Get-Date -format yyyyMMdd
$credential  = New-Object System.Management.Automation.PSCredential($username, (ConvertTo-SecureString $password -AsPlainText -Force))

# Login
Write-Host 'Logging in to Atlassian.'
Invoke-WebRequest -Method Post -Uri "https://$account.atlassian.net/login" -SessionVariable session -Body @{username = $username; password = $password} | Out-Null

# Request backup
Write-Host 'Triggering backup.'
Invoke-RestMethod -Method Post -Uri "https://$account.atlassian.net/wiki/rest/obm/1.0/runbackup" -WebSession $session -ContentType 'application/json' -Body (@{cbAttachments = $attachments} | ConvertTo-Json -Compress) | Out-Null

# Wait for backup to finish
Write-Host 'Waiting for backup generation to finish.'
do {
    $status = Invoke-RestMethod -Method Get -Uri "https://$account.atlassian.net/wiki/rest/obm/1.0/getprogress" -WebSession $session
    $status.alternativePercentage -match "(\d+)"
    Write-Progress -Activity 'Creating backup' -Status $status.alternativePercentage -PercentComplete $Matches[1]
    Start-Sleep -Seconds 5
} while(! $status.fileName)

# Download the backup
Write-Host "Downloading backup https://$account.atlassian.net/wiki/download/$($status.fileName)"
Invoke-WebRequest "https://$account.atlassian.net/wiki/download/$($status.fileName)" -WebSession $session -OutFile (Join-Path -Path $destination -ChildPath "Confluence-backup-$today.zip")
Write-Host 'Pinging Cronitor.'
Invoke-WebRequest "https://cronitor.link/$cronitor/complete" | Out-Null
Write-Host 'Backup complete.' -ForegroundColor Green

```

**Comment by pavlovps** [comment]
@abrookewood thanks for the script!
In order to get Jira backup there are few changes required besides changing urls you mentioned. At least for our instance of Jira backup still remains in webdav and it requires credentials to be passed once again, not session:
`Invoke-WebRequest "https://$account.atlassian.net/**webdav/backupmanager**/$($status.fileName)" -**Credential $credential** -OutFile (Join-Path -Path $destination -ChildPath $jiraBackupFile)`

**Comment by abrookewood** [comment]
Yes, this is only if you are on the new method (filestore).

Regards,

Antony Brooke-Wood
Mobile: +61 404 460 326

**Comment by herrrey** [comment]
It’s interesting to see how even in technology, changes require careful planning and awareness of the processes involved — much like life itself. [Surah Yasin](https://suraheyaseen.com/), often called the “Heart of the Qur’an,” reminds us of the importance of reflection, foresight, and preparation. Just as we approach life’s challenges with understanding and caution, updates like Atlassian’s cloud backup changes highlight the need to adapt thoughtfully and responsibly. Both in faith and in work, awareness and careful action are key to avoiding unexpected issues.
